### ISSUE TITLE
build instructions available?

### ISSUE THREAD

**Issue by dahliaT** [vinzenz/libomvtk#1]
Are there any instructions available for building? I found some scripts that have a .lua extension but they don't seem to work with any lua interpreter I have and I don't really know lua. I can't find any makefiles or other build tools I'm familiar with.

**Comment by vinzenz** [comment]
Well please note that the project is basically dead. However:

The build tool used here is premake. http://industriousone.com/premake/download

 You would go to the libomvtk folder, and run premake4 'action' (http://industriousone.com/premake-quick-start)
Where action is your preferred target. e.g. vs2008 or gmake

In case of gmake you simply run make afterwards, or if you generate Visual Studio projects then you'd open Visual Studio with the generated solution and go from there.
